### ISSUE TITLE
Could not make sense of the given file. Did you install the module to support this type of file ?

### ISSUE THREAD

**Issue by sjain17** [OCA/bank-statement-import#122]
Could not make sense of the given file.
Did you install the module to support this type of file?

Using QIF file from an Indian Bank

**Comment by pedrobaeza** [comment]
Please show Odoo log, and having the file would also help.

**Comment by sjain17** [comment]
There is nothing in the log which is related to the above error. This is the only thing which comes up when I click on Import button after uploading the file. 

Is there any python dependencies which I need to install before using this module. I am using Ubuntu 14.04 with Odoo 9 CE.

**Comment by pedrobaeza** [comment]
Nop.

**Comment by sjain17** [comment]
Can we have a quick call to discuss this?

**Comment by pedrobaeza** [comment]
Sorry, no. This is not a free support.

**Comment by pthiry** [comment]
Try saving the QIF file as UTF without BOM (byte order mark).  I had the same error message because the file had ```\xef\xbb\xbf``` at the start of the file.  

```data_file.strip().startswith('!Type:')``` fails with a byte order mark [here](https://github.com/OCA/bank-statement-import/blob/aefe0aa78f082812b5fc0b661d8bc0a46a55b648/account_bank_statement_import_qif/wizards/account_bank_statement_import_qif.py#L21)

```python
    @api.model
    def _check_qif(self, data_file):
        return data_file.strip().startswith('!Type:')
```


 * Import works after I saved the QIF file without the byte order mark

**Comment by rubencabrera** [comment]
@pthiry's answer worked for me. For anyone else experiencing this, it's easy to save a file without BOM using vim from the command line:
```
vim name_of_the_file.qif "+set nobomb" "+wq"
```
