### ISSUE TITLE
acc_number vs. sanitized_acc_number

### ISSUE THREAD

**Issue by hbrunn** [OCA/bank-statement-import#34]
I'm a bit bothered by the data duplication that `sanitized_acc_number` introduces and the hoops we've got to jump through in https://github.com/OCA/bank-statement-import/blob/8.0/account_bank_statement_import/res_partner_bank.py#L49 to make it work as users would expect.

What is the rationale behind this?

If it's only for reliably finding the right account number, I'd suggest the following:
- [ ] sanitize existing account numbers in an init hook
- [ ] sanitize input during `create` and `write`
- [ ] provide a form/tree widget for pretty formatting of IBANs (that is made is a way to be easily overridden in localization modules)
- [ ] provide a search widget that sanitizes IBANs for searching

What do you think?

**Comment by pedrobaeza** [comment]
I prefer also this approach to avoid a field duality with pretty same data, but requires all the tasks you have mentioned done.

**Comment by lmignon** [comment]
@hbrunn with this kind of change you need to
- override all the views/ search using the account number,
- fix all the generated documents displaying this field,
- duplicate the logic behind sanitize on the server side and the client side.
- keep the same hoops in the search method since this method is called from other modules to avoid that each caller must sanitize the value in its search domain before calling the method.

IMO, it's a lot of changes in a lot of code for the same result.

**Comment by pedrobaeza** [comment]
But if we put a normalized form, all places will put the same string, so no need for all you say, @lmignon

**Comment by hbrunn** [comment]
I _think_ if we inherit from `fields.Char` to create a `fields.IBAN`, we can make our iban-widget the default widget for all view types mentioned, then changing views would not be an issue. For qweb reports, the same applies I think.

For the last point: Please have the user of `search` sanitize the input. I'm not sure if this happens in real life, but the current code would change my search for Dutch account numbers `('acc_number', 'ilike', 'NL*')` to `('sanitized_acc_number', 'ilike', '*NL*')`, which might find a lot more than we want. Yes, of course we can adapt the search function, but still, I'd like to avoid this.

**Comment by lmignon** [comment]
@hbrunn a new field type seems a good idea but it break the current api. 

For the last point, my main concern is to put in place a way that ensue that querying an acc_number from the UI or from inside the code doesn't require  that you have to sanitize the value. Before this change we had to fix some errors in the code because the developers forgot to sanitize the account number. 

I've experimented a lot of way to find an other solution to 'normalize' the account number but that's the only one I found to not break existing installations. I'll be happy if we can find an other one.
