### ISSUE TITLE
Online Bank Statement Providers - Journal/currency/service/... fields missing

### ISSUE THREAD

**Issue by RBDSeb** [OCA/bank-statement-import#578]
Hello,

Not sure it is a bug (I think this is more a misusage from my side) 

## Module  
account_statement_import_online

## Describe the bug
**affected version : 15.0.**

On the creation of a "online bank statement providers", Journal/currency/Sanitized account number/Service dont have a field 
![image](https://user-images.githubusercontent.com/112514413/225310864-4395db34-d74e-4d50-91db-a8abacb4b95f.png)

Also I cannot activate "bank feeds" as I don't is it in bank account options...(actually from "invoicing" I do have only "add bank account" and not "bank account")
![image](https://user-images.githubusercontent.com/112514413/225311570-84941a4c-8a39-4a4e-ab68-e2a0d5081c66.png)

Thanks!

**Comment by kwoychesko** [comment]
Hello!
Regarding the missing field, I think this is because you've tried to create the record by clicking "Create" on the view of Online Bank Statement Providers (i.e. you probably clicked _Invoicing > Configuration > Banks > Online Bank Statement Providers_ and then clicked _Create_.) I'm not sure why this button exists, honestly — it's not the way to create a provider (at least anymore... in older versions of Odoo it might have worked). The proper way to create a provider is to create the Bank Account & Journal first, and then to configure the provider. Here are the instructions if using PayPal:

1. Go to _Invoicing > Configuration > Banks > Add a Bank Account_.
2. Fill in the Account Number (and other fields if desired) and click _Create_. NOTE: From my experience with PayPal, this account number is not used in the authentication with PayPal's server (not sure about other online providers though). When I configure the account for PayPal, I usually just use the email address of the PayPal login.
1. Go to _Invoicing > Configuration > Accounting > Journals_.
3. Open and Edit the Journal corresponding to the bank account created automatically when you created the Bank Account above.
5. Set Bank Feeds to _Online (OCA)_.
6. Select the desired online bank statements provider in the _Online Bank Statements (OCA)_ section. (e.g. PayPal.com)
7. Save the Journal.
8. Click on the provider to configure provider-specific settings and click _Edit_.
9. Fill in your desired _Configuration_ and _Scheduled Pull_ settings.
10. Leave the _API base_ field empty, and fill in the _Client ID_ and _Secret_ from your PayPal Developer account.
11. Click Save.

You can now either manually pull the latest statements or wait for the scheduled run.
