### ISSUE TITLE
CAMT statement without transactions fail to import

### ISSUE THREAD

**Issue by philhug** [OCA/bank-statement-import#93]
Importing a camt.053 without any transactions fail to import.
e.g. a statement with only an opening and closing balance.

this is due to the following check:
account_bank_statement_import_camt/camt.py in def parse
```
        for node in root[0][1:]:
            statement = self.parse_statement(ns, node)
            **if len(statement['transactions']):**
                if 'currency' in statement:
                    currency = statement.pop('currency')
                if 'account_number' in statement:
                    account_number = statement.pop('account_number')
                statements.append(statement)
        return currency, account_number, statements
```

I will create a PR to remove this check. Or is there a specific reason for this check?

**Comment by ghost** [comment]
[bank statements with no transactions don't exist in the eyes of Odoo,](https://github.com/odoo/odoo/blob/10.0/addons/account_bank_statement_import/account_bank_statement_import.py#L119) and even if you were to override this last check you would run into trouble because [Odoo would decide that the current file is a duplicate.](https://github.com/odoo/odoo/blob/10.0/addons/account_bank_statement_import/account_bank_statement_import.py#L232) With that said, I ran into the same issue today, and it's probably common for a bank to issue a statement saying "nothing happened" if the client wants end-of-day camt.053 files.  It's also the case that empty camts still tell you the account number and currency. Maybe Odoo core should add a boolean flag to allow empty statements? I'm not confident enough to propose that upstream yet, but if our bank keeps doing it, maybe Odoo should support it.
